version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
        - MYSQL_DATABASE=db_devops
        - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  rest_app:
    build: .
    command: python3 rest_app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - "db:db_devops"

